version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/zeus-api
hooks:
  BeforeInstall:
    - location: script/hoge.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/hoge.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/deploy.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: script/hoge.sh
      timeout: 300
      runas: root
