spring:
  datasource:
    batch-mysql:
      jdbcUrl: jdbc:mysql://localhost:23307/batch
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
