name: "constant"
description: 'constant'
outputs:
  java-version:
    value: ${{ steps.constant.outputs.java-version }}
  java-distribution:
    value: ${{ steps.constant.outputs.java-distribution }}
  gradle-version:
    value: ${{ steps.constant.outputs.gradle-version }}
runs:
  using: "composite"
  steps:
    - id: constant
      run: |
        echo "::set-output name=java-version::17"
        echo "::set-output name=java-distribution::temurin"
        echo "::set-output name=gradle-version::7.4.2"
      shell: bash
