openapi: 3.0.0
info:
  title: net-api
  description: api created by ningenme
  version: 1.0.0
servers:
  - url: https://api.ningenme.net
paths:
  /v1/health:
    $ref: './paths/Health.yaml'
  /v1/application-metas/{applicationMetaId}/latest:
    $ref: './paths/ApplicationMetaLatest.yaml'
  /v1/application-metas/{applicationMetaId}:
    $ref: './paths/ApplicationMeta.yaml'
  /v1/access-counts:
    $ref: './paths/AccessCount.yaml'

