name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.constant.outputs.java-version }}
      java-distribution: ${{ steps.constant.outputs.java-distribution }}
      gradle-version: ${{ steps.constant.outputs.gradle-version }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: constant
        name: constant
        uses: ./.github/workflows/composite/constant
  git-diff:
    runs-on: ubuntu-latest
    outputs:
      ci: ${{ steps.git-diff-ci.outputs.diff-count }}
      api: ${{ steps.git-diff-api.outputs.diff-count }}
      batch: ${{ steps.git-diff-batch.outputs.diff-count }}
      domain: ${{ steps.git-diff-domain.outputs.diff-count }}
      infrastructure: ${{ steps.git-diff-infrastructure.outputs.diff-count }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: git-diff-ci
        name: git diff ci
        uses: ./.github/workflows/composite/git-diff
        with:
          subdir: .github
      - id: git-diff-api
        name: git diff api
        uses: ./.github/workflows/composite/git-diff
        with:
          subdir: zeus/api
      - id: git-diff-batch
        name: git diff batch
        uses: ./.github/workflows/composite/git-diff
        with:
          subdir: zeus/batch
      - id: git-diff-domain
        name: git diff domain
        uses: ./.github/workflows/composite/git-diff
        with:
          subdir: zeus/domain
      - id: git-diff-infrastructure
        name: git diff infrastructure
        uses: ./.github/workflows/composite/git-diff
        with:
          subdir: zeus/infrastructure

  github:
    runs-on: ubuntu-latest
    needs: [ constant, git-diff ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: assignees
        name: assignees
        uses: actions/github-script@v4.1.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: `${{ github.actor }}`
            });

  gradle-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project-name: ":zeus:api"
            has-diff: ${{ needs.git-diff.outputs.api > 0 }}
          - project-name: ":zeus:batch"
            has-diff: ${{ needs.git-diff.outputs.batch > 0 }}
          - project-name: ":zeus:domain"
            has-diff: ${{ needs.git-diff.outputs.domain > 0 }}
          - project-name: ":zeus:infrastructure"
            has-diff: ${{ needs.git-diff.outputs.infrastructure > 0 }}
    name: gradle-check${{ matrix.project-name }}
    needs: [ constant, git-diff, github ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: gradle-check
        name: gradle check
        if: ${{ matrix.has-diff }}
        uses: ./.github/workflows/composite/gradle-check
        with:
          java-version: ${{ needs.constant.outputs.java-version }}
          java-distribution: ${{ needs.constant.outputs.java-distribution }}
          gradle-version: ${{ needs.constant.outputs.gradle-version }}
          project-name: ${{ matrix.project-name }}
